### ISSUE TITLE
traceback caused by #59

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#66]
traceback caused by #59 

{{{
From: root@localhost root@localhost
Reply: root@localhost root@localhost
Date: March 3, 2014 at 10:20:30 AM

To: emperorcezar@gmail.com emperorcezar@gmail.com
Subject:  [Django] ERROR (EXTERNAL IP): Internal Server Error: /meetings/ical/ 
Traceback (most recent call last): 

File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response 
response = callback(request, _callback_args, *_callback_kwargs) 

File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/syndication/views.py", line 38, in **call** 
feedgen = self.get_feed(obj, request) 

File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/syndication/views.py", line 184, in get_feed 
**self.item_extra_kwargs(item) 

File "/app/.heroku/python/lib/python2.7/site-packages/django_ical/views.py", line 110, in item_extra_kwargs 
val = self._get_dynamic_attr('item_' + field, obj) 

File "/app/.heroku/python/lib/python2.7/site-packages/django_ical/views.py", line 84, in _get_dynamic_attr 
return attr(obj) 

File "/app/chipy_org/apps/meetings/feeds.py", line 32, in item_location 
return item.where.address 

AttributeError: 'NoneType' object has no attribute 'address' 

<WSGIRequest 
path:/meetings/ical/, 
GET:<QueryDict: {}>, 
POST:<QueryDict: {}>, 
COOKIES:{}, 
META:{'CSRF_COOKIE': xxxx', 
'HTTP_ACCEPT': '_/_', 
'HTTP_ACCEPT_ENCODING': 'gzip,deflate', 
'HTTP_CONNECTION': 'close', 
'HTTP_FROM': 'googlebot(at)googlebot.com', 
'HTTP_HOST': 'www.chipy.org', 
'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', 
'HTTP_X_FORWARDED_FOR': 'xxxxx
'HTTP_X_FORWARDED_PORT': '80', 
'HTTP_X_FORWARDED_PROTO': 'http', 
'HTTP_X_REQUEST_ID':xxxxx, 
'HTTP_X_REQUEST_START': '1393863629007', 
'PATH_INFO': u'/meetings/ical/', 
'QUERY_STRING': '', 
'RAW_URI': '/meetings/ical/', 
'REMOTE_ADDR': 'xxxxxx
'REMOTE_PORT': '48777', 
'REQUEST_METHOD': 'GET', 
'SCRIPT_NAME': u'', 
'SERVER_NAME': 'www.chipy.org', 
'SERVER_PORT': '80', 
'SERVER_PROTOCOL': 'HTTP/1.1', 
'SERVER_SOFTWARE': 'gunicorn/0.17.4', 
'gunicorn.socket': <socket._socketobject object at 0x18a72f0>, 
'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fca0083c1e0>, 
'wsgi.file_wrapper': <class gunicorn.http.wsgi.FileWrapper at 0x1c77ce8>, 
'wsgi.input': <gunicorn.http.body.Body object at 0x2b32a10>,

}}}
